import { drizzle } from 'drizzle-orm/better-sqlite3';
import Database from 'better-sqlite3';
import { jobs } from '../schema/jobs';

export async function seedJobs(
  db: ReturnType<typeof drizzle>, 
  companyUserIds: string[], 
  industryIds: string[]
) {
  console.log('💼 Seeding jobs...');

  const jobsData = [
    {
      title: 'Senior Frontend Developer',
      description: 'We are looking for a talented senior frontend developer to join our dynamic team. You will be responsible for building responsive web applications using modern JavaScript frameworks and ensuring excellent user experiences across all devices.',
      requirements: '<p><strong>Required Skills:</strong></p><ul><li>5+ years of experience with React and TypeScript</li><li>Strong understanding of modern web development practices</li><li>Experience with state management libraries (Redux, Zustand)</li><li>Proficiency in CSS-in-JS solutions and styling frameworks</li><li>Knowledge of testing frameworks (Jest, React Testing Library)</li><li>Experience with build tools and bundlers (Webpack, Vite)</li></ul><p><strong>Nice to Have:</strong></p><ul><li>Next.js experience</li><li>GraphQL knowledge</li><li>Performance optimization experience</li></ul>',
      responsibilities: '<p><strong>Key Responsibilities:</strong></p><ul><li>Build responsive and performant web applications</li><li>Collaborate with design and backend teams to implement features</li><li>Write clean, maintainable, and well-tested code</li><li>Mentor junior developers and conduct code reviews</li><li>Participate in architectural decisions and technical planning</li><li>Optimize applications for maximum speed and scalability</li></ul>',
      companyId: companyUserIds[0],
      locationType: 'hybrid',
      stateId: 'CA',
      cityId: 'CA.SF',
      districtId: 'CA.SF.SOMA',
      jobType: 'full-time',
      experienceLevel: 'senior',
      educationLevel: 'bachelor',
      industryId: industryIds[0], // Technology
      salaryMin: 140000,
      salaryMax: 200000,
      salaryCurrency: 'USD',
      skillsRequired: JSON.stringify(['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Redux', 'Jest']),
      benefits: JSON.stringify(['Health insurance', '401k matching', 'Remote work flexibility', 'Stock options', 'Learning budget']),
      status: 'published',
    },
    {
      title: 'Product Manager',
      description: 'Join our product team to help build amazing user experiences that delight our customers. You will work closely with engineering, design, and business stakeholders to define and execute product strategy.',
      requirements: '<p><strong>Required Qualifications:</strong></p><ul><li>3+ years of product management experience</li><li>Strong analytical and problem-solving skills</li><li>Excellent communication and presentation abilities</li><li>Experience with product analytics tools</li><li>Understanding of agile development methodologies</li><li>Data-driven decision making approach</li></ul>',
      responsibilities: '<p><strong>What You\'ll Do:</strong></p><ul><li>Define product roadmap and strategy</li><li>Work with engineering and design teams to deliver features</li><li>Conduct user research and gather customer feedback</li><li>Analyze product metrics and user behavior</li><li>Create and maintain product requirements documents</li><li>Coordinate product launches and go-to-market strategies</li></ul>',
      companyId: companyUserIds[1],
      locationType: 'onsite',
      stateId: 'NY',
      cityId: 'NY.NYC',
      districtId: 'NY.NYC.MAN',
      jobType: 'full-time',
      experienceLevel: 'mid',
      educationLevel: 'bachelor',
      industryId: industryIds[0], // Technology
      salaryMin: 110000,
      salaryMax: 150000,
      salaryCurrency: 'USD',
      skillsRequired: JSON.stringify(['Product Management', 'Agile', 'User Research', 'Data Analysis', 'Figma', 'SQL']),
      benefits: JSON.stringify(['Competitive salary', 'Flexible hours', 'Stock options', 'Health insurance', 'Professional development']),
      status: 'published',
    },
    {
      title: 'DevOps Engineer',
      description: 'We are seeking a skilled DevOps engineer to help us scale our infrastructure and improve our deployment processes. You will work with cutting-edge cloud technologies and automation tools.',
      requirements: '<p><strong>Technical Requirements:</strong></p><ul><li>3+ years of DevOps/SRE experience</li><li>Strong experience with AWS/Azure/GCP</li><li>Proficiency with containerization (Docker, Kubernetes)</li><li>Experience with Infrastructure as Code (Terraform, CloudFormation)</li><li>Knowledge of CI/CD pipelines and automation</li><li>Scripting skills (Python, Bash, PowerShell)</li></ul>',
      responsibilities: '<p><strong>Responsibilities:</strong></p><ul><li>Design and maintain cloud infrastructure</li><li>Implement and improve CI/CD pipelines</li><li>Monitor system performance and reliability</li><li>Automate deployment and scaling processes</li><li>Collaborate with development teams on infrastructure needs</li><li>Implement security best practices</li></ul>',
      companyId: companyUserIds[2],
      locationType: 'remote',
      jobType: 'full-time',
      experienceLevel: 'mid',
      educationLevel: 'bachelor',
      industryId: industryIds[0], // Technology
      salaryMin: 120000,
      salaryMax: 160000,
      salaryCurrency: 'USD',
      skillsRequired: JSON.stringify(['AWS', 'Kubernetes', 'Docker', 'Terraform', 'Jenkins', 'Python', 'Monitoring']),
      benefits: JSON.stringify(['Remote work', 'Health insurance', 'Learning budget', '401k', 'Flexible schedule']),
      status: 'published',
    },
    {
      title: 'Financial Analyst',
      description: 'Looking for a detail-oriented financial analyst to join our finance team. You will be responsible for financial modeling, analysis, and reporting to support business decisions.',
      requirements: '<p><strong>Qualifications:</strong></p><ul><li>2+ years of financial analysis experience</li><li>Strong proficiency in Excel and financial modeling</li><li>Knowledge of accounting principles and financial statements</li><li>Experience with financial software and databases</li><li>Analytical mindset with attention to detail</li><li>Strong communication and presentation skills</li></ul>',
      responsibilities: '<p><strong>Key Duties:</strong></p><ul><li>Conduct financial analysis and reporting</li><li>Support budgeting and forecasting processes</li><li>Develop and maintain financial models</li><li>Analyze business performance and trends</li><li>Prepare presentations for management</li><li>Support ad-hoc financial projects</li></ul>',
      companyId: companyUserIds[3],
      locationType: 'hybrid',
      stateId: 'NY',
      cityId: 'NY.NYC',
      districtId: 'NY.NYC.MAN',
      jobType: 'full-time',
      experienceLevel: 'junior',
      educationLevel: 'bachelor',
      industryId: industryIds[1], // Finance
      salaryMin: 70000,
      salaryMax: 95000,
      salaryCurrency: 'USD',
      skillsRequired: JSON.stringify(['Financial Analysis', 'Excel', 'SQL', 'Python', 'PowerBI', 'Accounting']),
      benefits: JSON.stringify(['Health insurance', 'Bonus potential', 'Professional development', '401k matching']),
      status: 'published',
    },
    {
      title: 'UX/UI Designer',
      description: 'We are looking for a creative UX/UI designer to help us create intuitive and beautiful user experiences. You will work closely with product and engineering teams.',
      requirements: '<p><strong>Requirements:</strong></p><ul><li>3+ years of UX/UI design experience</li><li>Strong portfolio demonstrating design process</li><li>Proficiency in design tools (Figma, Sketch, Adobe Creative Suite)</li><li>Understanding of user-centered design principles</li><li>Experience with prototyping and wireframing</li><li>Knowledge of design systems and accessibility</li></ul>',
      responsibilities: '<p><strong>What You\'ll Do:</strong></p><ul><li>Create user-centered designs for web and mobile</li><li>Conduct user research and usability testing</li><li>Develop wireframes, prototypes, and high-fidelity designs</li><li>Collaborate with product managers and developers</li><li>Maintain and evolve design systems</li><li>Present design concepts to stakeholders</li></ul>',
      companyId: companyUserIds[0],
      locationType: 'hybrid',
      stateId: 'CA',
      cityId: 'CA.LA',
      districtId: 'CA.LA.SANTA',
      jobType: 'full-time',
      experienceLevel: 'mid',
      educationLevel: 'bachelor',
      industryId: industryIds[0], // Technology
      salaryMin: 90000,
      salaryMax: 130000,
      salaryCurrency: 'USD',
      skillsRequired: JSON.stringify(['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Adobe Creative Suite']),
      benefits: JSON.stringify(['Creative environment', 'Health insurance', 'Flexible work', 'Design conference budget']),
      status: 'published',
    },
    {
      title: 'Data Scientist',
      description: 'Join our data team to help extract insights from large datasets and build machine learning models that drive business decisions.',
      requirements: '<p><strong>Required Skills:</strong></p><ul><li>PhD in Computer Science, Statistics, or related field</li><li>3+ years of data science experience</li><li>Strong programming skills in Python/R</li><li>Experience with machine learning frameworks</li><li>Knowledge of statistical analysis and modeling</li><li>Experience with big data technologies</li></ul>',
      responsibilities: '<p><strong>Responsibilities:</strong></p><ul><li>Develop and deploy machine learning models</li><li>Analyze large datasets to extract insights</li><li>Collaborate with engineering to implement solutions</li><li>Create data visualizations and reports</li><li>Design and run A/B tests</li><li>Stay current with latest ML/AI research</li></ul>',
      companyId: companyUserIds[2],
      locationType: 'remote',
      jobType: 'full-time',
      experienceLevel: 'senior',
      educationLevel: 'phd',
      industryId: industryIds[0], // Technology
      salaryMin: 150000,
      salaryMax: 220000,
      salaryCurrency: 'USD',
      skillsRequired: JSON.stringify(['Python', 'Machine Learning', 'TensorFlow', 'SQL', 'Statistics', 'Pandas', 'Jupyter']),
      benefits: JSON.stringify(['Remote work', 'Stock options', 'Conference budget', 'Research time', 'Top-tier compensation']),
      status: 'published',
    },
    {
      title: 'Backend Engineer',
      description: 'We need a skilled backend engineer to help build scalable APIs and services that power our applications.',
      requirements: '<p><strong>Technical Requirements:</strong></p><ul><li>4+ years of backend development experience</li><li>Strong knowledge of Java/Python/Go</li><li>Experience with microservices architecture</li><li>Database design and optimization skills</li><li>Understanding of distributed systems</li><li>Experience with cloud platforms</li></ul>',
      responsibilities: '<p><strong>Key Responsibilities:</strong></p><ul><li>Design and implement RESTful APIs</li><li>Build scalable microservices</li><li>Optimize database queries and performance</li><li>Implement security best practices</li><li>Write comprehensive tests</li><li>Participate in system architecture decisions</li></ul>',
      companyId: companyUserIds[1],
      locationType: 'hybrid',
      stateId: 'TX',
      cityId: 'TX.AUS',
      districtId: 'TX.AUS.DT',
      jobType: 'full-time',
      experienceLevel: 'senior',
      educationLevel: 'bachelor',
      industryId: industryIds[0], // Technology
      salaryMin: 130000,
      salaryMax: 180000,
      salaryCurrency: 'USD',
      skillsRequired: JSON.stringify(['Java', 'Spring Boot', 'PostgreSQL', 'Redis', 'Kafka', 'Docker', 'AWS']),
      benefits: JSON.stringify(['Competitive salary', 'Stock options', 'Health insurance', 'Learning budget', 'Flexible hours']),
      status: 'published',
    },
    {
      title: 'Marketing Manager',
      description: 'Lead our marketing efforts to drive brand awareness and customer acquisition. You will develop and execute comprehensive marketing strategies.',
      requirements: '<p><strong>Qualifications:</strong></p><ul><li>3+ years of marketing experience</li><li>Strong understanding of digital marketing channels</li><li>Experience with marketing automation tools</li><li>Data-driven approach to marketing</li><li>Excellent written and verbal communication</li><li>Project management skills</li></ul>',
      responsibilities: '<p><strong>What You\'ll Do:</strong></p><ul><li>Develop and execute marketing strategies</li><li>Manage digital marketing campaigns</li><li>Analyze marketing performance and ROI</li><li>Collaborate with sales and product teams</li><li>Create marketing content and materials</li><li>Manage marketing budget and resources</li></ul>',
      companyId: companyUserIds[3],
      locationType: 'onsite',
      stateId: 'IL',
      cityId: 'IL.CHI',
      districtId: 'IL.CHI.LOOP',
      jobType: 'full-time',
      experienceLevel: 'mid',
      educationLevel: 'bachelor',
      industryId: industryIds[7], // Marketing & Advertising
      salaryMin: 80000,
      salaryMax: 110000,
      salaryCurrency: 'USD',
      skillsRequired: JSON.stringify(['Digital Marketing', 'Google Analytics', 'SEO', 'Content Marketing', 'Social Media', 'HubSpot']),
      benefits: JSON.stringify(['Health insurance', 'Marketing conference budget', 'Flexible PTO', 'Bonus potential']),
      status: 'published',
    },
    {
      title: 'Software Engineer Intern',
      description: 'Summer internship opportunity for computer science students to gain hands-on experience in software development.',
      requirements: '<p><strong>Requirements:</strong></p><ul><li>Currently pursuing CS or related degree</li><li>Knowledge of programming fundamentals</li><li>Familiarity with at least one programming language</li><li>Strong problem-solving skills</li><li>Eagerness to learn and grow</li><li>Good communication skills</li></ul>',
      responsibilities: '<p><strong>Internship Activities:</strong></p><ul><li>Work on real software projects</li><li>Collaborate with experienced engineers</li><li>Participate in code reviews and team meetings</li><li>Learn about software development best practices</li><li>Contribute to product features</li><li>Present final project at end of internship</li></ul>',
      companyId: companyUserIds[0],
      locationType: 'hybrid',
      stateId: 'CA',
      cityId: 'CA.SF',
      districtId: 'CA.SF.FIN',
      jobType: 'internship',
      experienceLevel: 'entry',
      educationLevel: 'bachelor',
      industryId: industryIds[0], // Technology
      salaryMin: 6000,
      salaryMax: 8000,
      salaryCurrency: 'USD',
      skillsRequired: JSON.stringify(['Python', 'Java', 'Git', 'Problem Solving', 'Teamwork']),
      benefits: JSON.stringify(['Mentorship', 'Learning opportunities', 'Networking', 'Potential full-time offer']),
      status: 'published',
    },
    {
      title: 'Healthcare Data Analyst',
      description: 'Analyze healthcare data to improve patient outcomes and operational efficiency. Work with clinical and administrative datasets.',
      requirements: '<p><strong>Required Qualifications:</strong></p><ul><li>2+ years of healthcare data analysis experience</li><li>Knowledge of healthcare systems and terminology</li><li>Strong SQL and data analysis skills</li><li>Experience with healthcare databases</li><li>Understanding of HIPAA compliance</li><li>Statistical analysis experience</li></ul>',
      responsibilities: '<p><strong>Key Duties:</strong></p><ul><li>Analyze clinical and operational data</li><li>Create dashboards and reports for stakeholders</li><li>Identify trends and patterns in healthcare data</li><li>Support quality improvement initiatives</li><li>Ensure data privacy and compliance</li><li>Collaborate with clinical teams</li></ul>',
      companyId: companyUserIds[4],
      locationType: 'onsite',
      stateId: 'FL',
      cityId: 'FL.MIA',
      districtId: 'FL.MIA.DT',
      jobType: 'full-time',
      experienceLevel: 'junior',
      educationLevel: 'bachelor',
      industryId: industryIds[2], // Healthcare
      salaryMin: 65000,
      salaryMax: 85000,
      salaryCurrency: 'USD',
      skillsRequired: JSON.stringify(['SQL', 'Healthcare Analytics', 'Tableau', 'Python', 'HIPAA', 'Statistical Analysis']),
      benefits: JSON.stringify(['Health insurance', 'Retirement plan', 'Professional development', 'Healthcare discounts']),
      status: 'published',
    },
  ];

  const insertedJobs = await db.insert(jobs).values(jobsData).returning();

  console.log('✅ Jobs seeded successfully!');
  return insertedJobs;
}
